import assert from "node:assert/strict";
import test from "node:test";

import {
  buildRovingNotes,
  formatRoveSubtypesLabel,
  hasCustomShiftNotes,
  isAutoGeneratedRovingNote,
  normalizeRoveSubtypes,
} from "../src/rovingUtils.js";
import { makeShift } from "./fixtures.js";

test("normalizes legacy roving values and builds combined labels", () => {
  assert.deepEqual(normalizeRoveSubtypes(["R3", "R5", "R/B", "CSA"]), [
    "R-3",
    "R-5",
    "R-B",
    "CSA",
  ]);
  assert.equal(formatRoveSubtypesLabel(["R-3", "R-5"]), "R-3/5");
  assert.equal(formatRoveSubtypesLabel(["R-3", "R-5", "CSA"]), "R-3/5 + CSA");
  assert.equal(formatRoveSubtypesLabel(["R-B", "CSA"]), "R/B + CSA");
});

test("combines subtype descriptions and detects generated notes", () => {
  const notes = buildRovingNotes(["R-3", "R-5"]);

  assert.match(notes, /R-3 - General Mealtime Rove/);
  assert.match(notes, /R-5 - Monitor Laundry/);
  assert.equal(isAutoGeneratedRovingNote(notes), true);
  assert.equal(hasCustomShiftNotes(makeShift({ notes })), false);
});

test("preserves and detects custom manager notes", () => {
  const generated = buildRovingNotes(["R-3"]);
  const custom = `${generated}\n\nMeet the manager by the west door.`;

  assert.equal(isAutoGeneratedRovingNote(custom), false);
  assert.equal(hasCustomShiftNotes(makeShift({ notes: custom })), true);
  assert.equal(custom.endsWith("west door."), true);
});
