import { ROVING_SUBTYPE_NOTES, ROVING_SUBTYPES } from "./model.js";

export function normalizeRoveSubtype(value) {
  const normalized = String(value ?? "")
    .trim()
    .toUpperCase()
    .replace(/\s+/g, "")
    .replace(/^R(\d+)$/, "R-$1")
    .replace(/^R\/([BJ])$/, "R-$1");

  if (normalized === "RB") {
    return "R-B";
  }

  if (normalized === "RJ") {
    return "R-J";
  }

  return ROVING_SUBTYPES.includes(normalized) ? normalized : "";
}

export function normalizeRoveSubtypes(value, fallback = "") {
  const rawValues = Array.isArray(value)
    ? value
    : extractRoveSubtypeCandidates(value || fallback);
  const unique = new Set();

  for (const rawValue of rawValues) {
    const normalized = normalizeRoveSubtype(rawValue);

    if (normalized) {
      unique.add(normalized);
    }
  }

  return ROVING_SUBTYPES.filter((roveType) => unique.has(roveType));
}

export function getPrimaryRoveSubtype(roveSubtypes) {
  return normalizeRoveSubtypes(roveSubtypes)[0] ?? "";
}

export function getRoveSubtypeOptionLabel(roveType) {
  if (/^R-\d+$/.test(roveType)) {
    return roveType.replace("-", "");
  }

  if (roveType === "R-B") {
    return "R/B";
  }

  if (roveType === "R-J") {
    return "R/J";
  }

  return roveType;
}

export function getRoveSubtypeDisplayLabel(roveType) {
  if (roveType === "R-B") {
    return "R/B";
  }

  if (roveType === "R-J") {
    return "R/J";
  }

  return roveType;
}

export function formatRoveSubtypesLabel(roveSubtypes) {
  const normalized = normalizeRoveSubtypes(roveSubtypes);
  const numeric = normalized.filter((roveType) => /^R-\d+$/.test(roveType));
  const special = normalized.filter((roveType) => !/^R-\d+$/.test(roveType));
  const parts = [];

  if (numeric.length === 1) {
    parts.push(numeric[0]);
  } else if (numeric.length > 1) {
    const numbers = numeric.map((roveType) => roveType.replace("R-", ""));
    parts.push(`R-${numbers.join("/")}`);
  }

  parts.push(...special.map(getRoveSubtypeDisplayLabel));

  return parts.join(" + ");
}

export function isRovingAutoLabel(value) {
  const label = String(value ?? "").trim();

  if (!label) {
    return true;
  }

  return normalizeRoveSubtypes(label).length > 0;
}

export function buildRovingNotes(roveSubtypes) {
  return normalizeRoveSubtypes(roveSubtypes)
    .map((roveType) => {
      const description = ROVING_SUBTYPE_NOTES[roveType] ?? "";

      if (!description) {
        return "";
      }

      return `${getRoveSubtypeDisplayLabel(roveType)} - ${getRovingNoteTitle(description)}\n${description}`;
    })
    .filter(Boolean)
    .join("\n\n");
}

export function isAutoGeneratedRovingNote(value) {
  const note = String(value ?? "").trim();

  if (!note) {
    return false;
  }

  if (Object.values(ROVING_SUBTYPE_NOTES).includes(note)) {
    return true;
  }

  const generatedSections = new Set(
    ROVING_SUBTYPES.map((roveType) => buildRovingNotes([roveType])),
  );
  const sections = note.split(/\n{2,}/).map((section) => section.trim()).filter(Boolean);

  return sections.length > 0 && sections.every((section) => generatedSections.has(section));
}

export function hasCustomShiftNotes(shift) {
  const notes = shift.notes?.trim() ?? "";

  return Boolean(notes && !isAutoGeneratedRovingNote(notes));
}

function extractRoveSubtypeCandidates(value) {
  const text = String(value ?? "").trim();

  if (!text) {
    return [];
  }

  const compact = text.toUpperCase().replace(/\s+/g, "");

  if (/^R-?\d+(\/(?:R-?)?\d+)+$/.test(compact)) {
    return compact
      .split("/")
      .map((part, index) => (index === 0 ? part : `R-${part.replace(/^R-?/, "")}`));
  }

  if (/^R\d+(\/R\d+)+$/.test(compact)) {
    return compact.split("/");
  }

  const candidates = [];
  const numericGroups = text.match(/R-?\d+(?:\/(?:R-?)?\d+)*/gi) ?? [];

  for (const group of numericGroups) {
    const parts = group
      .toUpperCase()
      .split("/")
      .map((part, index) => (index === 0 ? part : `R-${part.replace(/^R-?/, "")}`));
    candidates.push(...parts);
  }

  candidates.push(...(text.match(/CSA|R[-/]?[BJ]/gi) ?? []));

  return candidates.length ? candidates : [text];
}

function getRovingNoteTitle(description) {
  return description.split(".")[0]?.trim() || "Roving";
}
